"""Write the files and open the pull request -- a resumable transaction, run by script not model.

Two reasons this is code rather than something the writing agent does:

* **It is the arbiter.** The model produces prose and nothing else; every mechanical step -- what
  the files contain, which paths change, what the commit says, which branch it lands on -- happens
  here, where it is tested. That is what makes "scripts decide everything decidable" true rather
  than aspirational.

* **It has to survive interruption.** `push` then `gh pr create` is two operations, and a worker can
  die between them, or lose the response to the second after GitHub has acted on it. A naive retry
  then either wedges on an existing branch or opens a duplicate. So the branch name is a pure
  function of the window, and every run reconciles what already exists before doing anything:

      no branch, no PR      -> commit, push, create
      branch, no PR         -> reuse the branch (update if the content differs), create
      our open PR           -> in flight; do nothing
      merged PR (anyone's)  -> already done; do nothing
      our closed, unmerged  -> someone rejected this window; do NOT reopen, report loudly

The last case matters: a rejected report must not come back by itself every day. So does the word
"our": anyone may open a pull request on a `progress/*` branch, and branch names are a pure function
of the window, so honouring a stranger's would let them decide what this operator is allowed to
publish -- permanently, by opening and closing one pull request.

Reconciling the window is not enough on its own, because an area can hold more than one open report
and the others are not reconciled by anything. Once ours is open we therefore close the area's
reports that can no longer merge -- see `superseded_prs` for the two ways that happens. Without it
the repository grows one unmergeable report per area per round and never sheds them.
"""

import json
import pathlib
import subprocess

from . import files, gh, layers as layers_mod

BRANCH_PREFIX = "progress/"
# Recorded in the PR body so a reader (and the merge gate) can tell which EpsilonEridaniProgress produced
# it. The gate, the worker and this module must all run the same version; see README.md.
BODY_MARKER = "<!--epsiloneridani-progress-pr:v1 {}-->"

EX_NOPROGRESS = 75


class ApplyError(RuntimeError):
    pass


def branch_name(plan):
    """`progress/<from7>-<to7>/<Area>`: a pure function of the window.

    Determinism is the whole point -- two workers computing the same window compute the same branch,
    so the second one finds the first one's work instead of duplicating it.
    """
    return (
        f"{BRANCH_PREFIX}{plan['from_sha'][:7]}-{plan['to_sha'][:7]}/{plan['roadmap']}"
    )


def pr_title(plan):
    """`progress: <Area> <date>`.

    The `progress:` prefix is load-bearing beyond readability: a squash merge carries the PR title
    into the commit subject, and the cheap `due` check finds the last update by scanning roadmap
    commit subjects for exactly this prefix.
    """
    date = (plan.get("to_date") or "")[:10]
    return f"progress: {plan['roadmap']} report for {date}".rstrip()


def pr_body(plan, section_header, version=None):
    """The PR description: what this covers, and enough metadata to audit it."""
    prs = ", ".join(f"#{n}" for n in sorted(plan["prs"]))
    meta = {
        "roadmap": plan["roadmap"],
        "from_sha": plan["from_sha"],
        "to_sha": plan["to_sha"],
        "prs": sorted(plan["prs"]),
        "version": version,
    }
    return (
        f"{BODY_MARKER.replace('{}', json.dumps(meta, sort_keys=True, separators=(',', ':')))}\n"
        f"This PR records progress on the {plan['roadmap']} roadmap for the window "
        f"`{plan['from_sha'][:7]}..{plan['to_sha'][:7]}` of EpsilonEridani `main`, covering "
        f"{len(plan['prs'])} merged pull requests.\n\n"
        f"`STATUS.md` is rewritten as a snapshot at `{plan['to_sha'][:7]}`; `PROGRESS.md` gains one "
        f"appended section for the window. Both files are machine-owned and their prose is not "
        f"security-validated.\n\n"
        f"Pull requests in the window: {prs}\n\n"
        f"Generated by [EpsilonEridaniProgress](https://github.com/eic/EpsilonEridaniProgress)"
        f"{f' at `{version}`' if version else ''}.\n\n"
        f"🤖 Prepared with Claude Code\n"
    )


def _run(args, cwd, check=True):
    proc = subprocess.run(args, cwd=str(cwd), capture_output=True, text=True)
    if check and proc.returncode != 0:
        raise ApplyError(
            f"{' '.join(args)} failed: {proc.stderr.strip() or proc.returncode}"
        )
    return proc


def _own_login():
    """The authenticated login, for scoping "did *I* already try this window?" lookups."""
    return gh.gh(["api", "user", "--jq", ".login"]).strip()


def own_pr(branch, repo=gh.ROADMAP_REPO, states=("open",)):
    """A pull request for `branch` that this operator could have opened, or None.

    "Could have opened" means its head is either in the canonical repository (we push there when we
    can) or in an account we control. Deliberately not "any pull request on this branch": branch
    names are a pure function of the window, so anyone can create one, and treating a stranger's as
    ours lets them decide what we may publish. See the callers for what each case would cost.

    Resolved without consulting `push_target`, so a dry run never creates a fork just to answer a
    question about existing pull requests.
    """
    ours = {repo.split("/")[0], _own_login()}
    for state in states:
        out = gh.gh(
            [
                "pr",
                "list",
                "--repo",
                repo,
                "--head",
                branch,
                "--state",
                state,
                "--limit",
                "20",
                "--json",
                "number,state,url,mergedAt,headRepositoryOwner",
            ]
        )
        for row in json.loads(out):
            if state == "closed" and row.get("mergedAt"):
                continue
            if ((row.get("headRepositoryOwner") or {}).get("login") or "") in ours:
                return row
    return None


def existing_pr(branch, repo=gh.ROADMAP_REPO, owner=None, states=("merged",)):
    """A pull request for `branch` from ANYONE, or None.

    Used only for the merged case, where authorship genuinely does not matter: if a report for this
    window has landed, the window is published no matter who published it. Every other question --
    is one in flight, was one refused -- must be scoped to our own, or a stranger could decide what
    we may publish. Use `own_pr` for those.
    """
    head = f"{owner}:{branch}" if owner else branch
    rows = []
    for state in states:
        out = gh.gh(
            [
                "pr",
                "list",
                "--repo",
                repo,
                "--head",
                head,
                "--state",
                state,
                "--limit",
                "20",
                "--json",
                "number,state,url,mergedAt,headRepositoryOwner",
            ]
        )
        rows.extend(json.loads(out))
    return rows[0] if rows else None


def report_meta(body):
    """The `epsiloneridani-progress-pr:v1` metadata a report carries in its body, or None.

    `pr_body` writes `from_sha`, `to_sha` and the window's PR numbers there, so a sibling states its
    own window exactly rather than in the seven-character abbreviations of a branch name. That is
    what makes a containment test possible without a EpsilonEridani clone.

    The body is mutable and anyone may edit it, so nothing here is trusted for a decision that could
    destroy work: the caller only ever uses it to prove that a report covers LESS than ours, and a
    forged wider claim merely spares a report from being closed.
    """
    marker = BODY_MARKER.split("{}")[0]
    for line in (body or "").splitlines():
        line = line.strip()
        if not line.startswith(marker):
            continue
        blob = line[len(marker) :]
        blob = blob[: blob.rfind("-->")] if "-->" in blob else blob
        try:
            meta = json.loads(blob)
        except json.JSONDecodeError:
            return None
        return meta if isinstance(meta, dict) else None
    return None


def superseded_prs(
    open_prs, area, live_cursor, plan_cursor, keep_branch, owners, our_prs=None
):
    """Open reports for `area` that this run's report replaces: `[(row, reason)]`.

    **Nothing is swept unless we are the live report.** `live_cursor` is read from the roadmap
    repository now; `plan_cursor` is where the cursor was when this run planned. If they differ, a
    sibling landed in between and it is OUR report that is dead, not anyone else's. Sweeping then
    inverts the rule below and closes the one report that can still merge, so the answer is to sweep
    nothing and let the next round reconcile.

    Given that, two things put a report beyond saving, and neither closes itself.

    **Its window no longer starts at the cursor.** The merge gate requires a byte-exact append at the
    cursor recorded in `PROGRESS.md`, so a report whose `from_sha` is not that cursor can never
    satisfy it -- dead by construction, not merely behind. This is what happens the moment a sibling
    for the same area merges: the cursor advances and every other open report is orphaned instantly.
    Nothing noticed, so they accumulated.

    **It starts at the cursor and we cover everything it covers.** Proved, not inferred: same
    `from_sha`, and its window's PR numbers are a proper subset of ours. Creation order will not do
    this job. A worker that planned early and stalled creates a NARROW report late, so "newest wins"
    would close a wider report and lose coverage that had already been written; and neither a
    timestamp nor a pull request number says anything about which window contains which. Containment
    is antisymmetric, so two workers racing cannot each conclude the other is dominated, and the
    stalled-worker case resolves correctly whichever of them opens first.

    A sibling whose window is incomparable to ours is left alone. So is every report, if `our_prs` is
    unknown: closing then would assert a containment we have not established, and a duplicate left
    for the next round is far cheaper than a report discarded.

    Scoped to reports we could have opened, like every other judgement in this module. Branch names
    are a pure function of the window, so a stranger can create one; closing theirs would let this
    operator silently veto someone else's contribution. The cost is real and worth naming: reports
    published from another operator's fork are never swept, so this does not by itself eliminate a
    multi-operator pile-up.
    """
    if not live_cursor or not plan_cursor or live_cursor != plan_cursor:
        return []
    ours = set(our_prs) if our_prs is not None else None
    out = []
    for row in open_prs:
        parts = (row.get("headRefName") or "").split("/")
        if len(parts) != 3 or parts[-1] != area:
            continue
        if row.get("headRefName") == keep_branch:
            continue
        if ((row.get("headRepositoryOwner") or {}).get("login") or "") not in owners:
            continue
        from7 = parts[1].split("-")[0] if "-" in parts[1] else ""
        if not from7:
            continue
        if not live_cursor.startswith(from7):
            out.append(
                (
                    row,
                    f"its window starts at {from7}, but the {area} cursor is now "
                    f"{live_cursor[:7]}, so it can never append",
                )
            )
            continue
        if ours is None:
            continue
        meta = report_meta(row.get("body"))
        if not meta or meta.get("from_sha") != live_cursor:
            continue
        try:
            theirs = {int(n) for n in (meta.get("prs") or [])}
        except (TypeError, ValueError):
            continue
        if theirs < ours:
            out.append(
                (
                    row,
                    f"its window covers {len(theirs)} of the {len(ours)} pull requests "
                    f"this one reports, from the same cursor {from7}",
                )
            )
    return out


def close_superseded(rows, replacement_url):
    """Close each superseded report, saying what replaced it. Returns the number that failed.

    A failure here is never fatal -- this only runs once the replacement is open, so the window is
    published either way -- but it is returned rather than swallowed, because the caller has to keep
    retrying. `sweep` is what makes that retry actually happen.
    """
    failed = 0
    for row, reason in rows:
        note = f"Superseded by {replacement_url}: {reason}."
        try:
            gh.gh(
                [
                    "pr",
                    "close",
                    str(row["number"]),
                    "--repo",
                    gh.ROADMAP_REPO,
                    "--comment",
                    note,
                ]
            )
            print(f"closed superseded #{row['number']}: {reason}")
        except gh.GhError as exc:
            failed += 1
            print(
                f"could not close superseded #{row['number']} ({exc}); leaving it open"
            )
    return failed


def sweep(plan, keep_branch, replacement_url):
    """Close the area's stranded reports. Safe to call whenever our report is open.

    Idempotent and deliberately reachable from BOTH paths in `run` -- the one that has just opened
    the report and the one that finds it already open. That is not tidiness: a sweep that only ran
    on the create path would never be retried at all, because the next run for the same window stops
    at the in-flight check long before reaching it. A cleanup outage would then leave the pile-up
    forever while every run reported success.

    Only `gh` failures are caught. A parsing or programming error here is a bug and must surface.
    """
    live = files.cursor(gh.file_on_default_branch(plan["progress_path"]) or "") or ""
    rows = superseded_prs(
        gh.open_progress_prs(),
        plan["roadmap"],
        live,
        plan["from_sha"],
        keep_branch,
        {gh.ROADMAP_REPO.split("/")[0], _own_login()},
        our_prs=plan.get("prs"),
    )
    if not rows:
        return 0
    return close_superseded(rows, replacement_url)


def remote_branch_exists(roadmap_dir, branch, remote="origin"):
    proc = _run(
        ["git", "ls-remote", "--exit-code", "--heads", remote, branch],
        roadmap_dir,
        check=False,
    )
    return proc.returncode == 0


def push_target(roadmap_dir, repo=gh.ROADMAP_REPO):
    """Where to push the report branch: `(remote_name, head_ref_for_pr)`.

    Publishing is open to anyone, so most operators will not have push access to the roadmap
    repository. They publish the ordinary way an outside contributor does, from a fork, and the merge
    check accepts fork heads: it never checks out pull-request content, and a fork's head commit and
    tree are replicated into the base repository, so the merge still builds from the validated bytes.

    Push access is checked rather than assumed because pushing to the canonical repository is
    preferable when it is available -- no fork to keep alive, and the branch is deleted after the
    merge -- and because discovering the answer by failing the push would waste the whole round.
    """
    if gh.gh(["api", f"repos/{repo}", "--jq", ".permissions.push"]).strip() == "true":
        return "origin", None

    # `--jq` emits raw values, not JSON: a login comes back as `kim-em`, unquoted. Do not `json.loads`
    # it -- that raises, and this is precisely the path an operator without push access takes.
    login = gh.gh(["api", "user", "--jq", ".login"]).strip()
    if not login:
        raise RuntimeError(
            "could not determine the authenticated login, so no fork can be used"
        )
    # `--clone=false` is idempotent: it creates the fork if absent and is a no-op if it exists.
    gh.gh(["repo", "fork", repo, "--clone=false", "--remote=false"])

    # Identify the fork by ANCESTRY, never by name. Two guesses would both be wrong: a fork can be
    # renamed, so `<login>/<name>` may not exist; and `<login>/<name>` may exist while being an
    # unrelated repository that merely shares the name, in which case a report would be pushed
    # somewhere it does not belong. `.parent.full_name` is the only field that actually answers
    # "is this a fork of the repository I mean?", so it is required in both branches below.
    #
    # `--paginate`, because the fork listing is ordered by creation and a popular repository's
    # first page says nothing about whether this account appears later.
    fork = (
        gh.gh(
            [
                "api",
                "--paginate",
                f"repos/{repo}/forks?per_page=100",
                "--jq",
                f'.[] | select(.owner.login == "{login}") | select(.parent.full_name == "{repo}") '
                f"| .full_name",
            ]
        )
        .strip()
        .splitlines()
    )
    fork = fork[0].strip() if fork else ""
    if not fork:
        candidate = f"{login}/{repo.split('/')[-1]}"
        parent = gh.gh(
            ["api", f"repos/{candidate}", "--jq", '.parent.full_name // ""']
        ).strip()
        fork = candidate if parent == repo else ""
    if not fork or "/" not in fork:
        raise RuntimeError(
            f"could not identify a fork of {repo} owned by {login}; publishing needs either push "
            f"access to {repo} or a fork of it"
        )
    url = f"https://github.com/{fork}.git"
    if (
        _run(["git", "remote", "get-url", "fork"], roadmap_dir, check=False).returncode
        == 0
    ):
        _run(["git", "remote", "set-url", "fork", url], roadmap_dir)
    else:
        _run(["git", "remote", "add", "fork", url], roadmap_dir)
    print(f"no push access to {repo}; publishing from {fork}")
    return "fork", fork.split("/")[0]


def render_update(plan, status_body, section_body, old_status, old_progress):
    """Build both files and validate them. Returns `(status_text, progress_text, section_header)`.

    Validation runs here, before anything is committed, so a malformed generation fails on the
    worker rather than becoming a pull request the gate has to reject.
    """
    area = plan["roadmap"]
    window_label = (
        f"{(plan.get('from_date') or '')[:10]} to {(plan.get('to_date') or '')[:10]}"
    )

    # The status prose ends with a ```coverage block, one line per layer the plan listed (for an
    # umbrella area, per layer of each sub-roadmap too). It becomes the coverage headers and leaves
    # the prose; a block that does not fit the plan's layers is refused here, so a half-right
    # assessment never reaches a pull request. So is a missing one when the plan lists layers: a
    # new report changes the report hash, which retires the site's hand transcription of the old
    # one, so a headerless report would turn assessed layers into unassessed ones. `unassessed` is
    # always available to the model when it cannot say. Only the worker insists; the gate still
    # accepts a status file without the header, as every report was before the header existed.
    prose, block = layers_mod.split_block(status_body)
    own_layers, sub_roadmaps = plan.get("layers") or [], plan.get("sub_roadmaps") or []
    coverage, sub_coverage = None, []
    if block is not None:
        if not own_layers and not sub_roadmaps:
            print(
                "the status body ends with a coverage block but the plan lists no layers; dropping it"
            )
        else:
            coverage, sub_coverage = layers_mod.coverage_block(
                area,
                plan["to_sha"],
                plan.get("readme_sha"),
                own_layers,
                sub_roadmaps,
                block,
            )
    elif own_layers or sub_roadmaps:
        count = len(own_layers) + sum(len(sub["layers"]) for sub in sub_roadmaps)
        raise files.FormatError(
            f"the status body has no ```coverage block, but the plan lists {count} layers "
            f"for {area}; every one needs a state, `unassessed` when the material does not say"
        )

    status_text = files.render_status(
        area, plan["to_sha"], plan.get("to_date") or "", prose, coverage, sub_coverage
    )
    section = files.render_section(
        area, plan["from_sha"], plan["to_sha"], plan["prs"], window_label, section_body
    )
    base_progress = (
        old_progress if old_progress is not None else files.new_progress_file(area)
    )
    progress_text = base_progress + section

    header = files.validate_update(
        area,
        old_status,
        status_text,
        base_progress,
        progress_text,
        expect_from_sha=plan["from_sha"],
    )
    return status_text, progress_text, header


def run(
    plan, status_body_file, section_body_file, roadmap_dir, dry_run=False, version=None
):
    """Write, commit, push and open the PR. Returns a process exit code."""
    roadmap_dir = pathlib.Path(roadmap_dir)
    branch = branch_name(plan)

    # --- reconcile before acting ---------------------------------------------------------------
    # A MERGED pull request from anyone is authoritative: the window is published, full stop.
    merged = existing_pr(branch, states=("merged",))
    if merged is not None:
        print(f"already merged: {merged['url']}")
        return EX_NOPROGRESS

    # An OPEN one only counts when we could have opened it. Branch names are a pure function of the
    # window, so honouring a stranger's would let anyone freeze a roadmap by opening one pull request
    # a day -- the staleness expiry in the planner bounds a single one, not a stream. A stranger's
    # report still merges on its own merits; it just does not stop us writing one. The cost is that
    # two operators publishing from their own forks may duplicate a window and waste a round, which
    # is much cheaper than being unable to report at all.
    open_pr = own_pr(branch, states=("open",))
    if open_pr is not None:
        print(f"already open, in flight: {open_pr['url']}")
        # Sweep here too. This is the path every run after the first takes, so it is the only one
        # that can retry a sweep an earlier run failed or never reached.
        try:
            sweep(plan, branch, open_pr.get("url") or "the open report")
        except gh.GhError as exc:
            print(
                f"could not sweep superseded reports ({exc}); the report is open regardless"
            )
        return EX_NOPROGRESS

    # A CLOSED pull request means this window was refused, and reopening it every day is the loop
    # this design avoids -- but only one WE could have opened may say so. Branch names are a pure
    # function of the window, so anyone can open and instantly close a pull request on that name;
    # honouring a stranger's would let them stop a window being published, permanently and silently.
    mine = own_pr(branch, states=("closed",))
    if mine is not None:
        print(
            f"this window was already proposed and closed unmerged ({mine['url']}); "
            f"refusing to reopen it. Land or delete that PR to unblock the area."
        )
        return EX_NOPROGRESS

    status_body = pathlib.Path(status_body_file).read_text(encoding="utf-8")
    section_body = pathlib.Path(section_body_file).read_text(encoding="utf-8")

    rel = plan["rel_dir"]
    status_path = roadmap_dir / plan["status_path"]
    progress_path = roadmap_dir / plan["progress_path"]
    if not (roadmap_dir / rel).is_dir():
        raise ApplyError(f"{rel} is not a directory in {roadmap_dir}")

    old_status = (
        status_path.read_text(encoding="utf-8") if status_path.is_file() else None
    )
    old_progress = (
        progress_path.read_text(encoding="utf-8") if progress_path.is_file() else None
    )

    status_text, progress_text, header = render_update(
        plan, status_body, section_body, old_status, old_progress
    )

    # --- commit on the deterministic branch ----------------------------------------------------
    _run(["git", "checkout", "-q", "-B", branch, "origin/main"], roadmap_dir)
    status_path.write_text(status_text, encoding="utf-8")
    progress_path.write_text(progress_text, encoding="utf-8")
    # Add only the two paths: an `add -A` here could sweep up anything else in the clone, and the
    # gate would (correctly) refuse the result.
    _run(["git", "add", "--", plan["status_path"], plan["progress_path"]], roadmap_dir)

    changed = _run(
        ["git", "diff", "--cached", "--name-only"], roadmap_dir
    ).stdout.split()
    if sorted(changed) != sorted([plan["status_path"], plan["progress_path"]]):
        raise ApplyError(
            f"staged paths are {changed}, expected exactly the two generated files"
        )

    title = pr_title(plan)
    body = pr_body(plan, header, version=version)
    _run(
        [
            "git",
            "commit",
            "-q",
            "-m",
            title,
            "-m",
            f"Window {plan['from_sha'][:7]}..{plan['to_sha'][:7]}",
        ],
        roadmap_dir,
    )

    if dry_run:
        diff = _run(
            ["git", "show", "--stat", "--format=%s", "HEAD"], roadmap_dir
        ).stdout
        print(f"[dry-run] branch {branch}\n{diff}")
        return 0

    # The branch already existing means a previous run (ours, or a peer racing us for the same window)
    # got this far and then died before opening the pull request. Leave its content alone and just open
    # the pull request for it: the branch name is a pure function of the window, so whatever is there is
    # a valid report for exactly this window, and overwriting it could clobber a peer's push moments
    # after it happened. Only push when nothing is there, and create-only so a concurrent push loses
    # rather than being silently overwritten.
    # Resolved here, after the dry-run return, because it can create a fork as a side effect.
    remote, fork_owner = push_target(roadmap_dir)
    if remote_branch_exists(roadmap_dir, branch, remote):
        print(
            f"branch {branch} already exists on {remote} (an earlier run was interrupted); "
            f"opening the pull request for it rather than rewriting it"
        )
    else:
        proc = _run(
            ["git", "push", remote, f"HEAD:refs/heads/{branch}"],
            roadmap_dir,
            check=False,
        )
        if proc.returncode != 0:
            # Most likely a peer created the same branch between the check and the push. That is fine:
            # fall through and let the pull-request step reconcile.
            print(
                f"create-only push declined ({proc.stderr.strip()[:200]}); reconciling instead"
            )

    # Re-check between push and create: another worker may have opened the PR for this exact window
    # in the meantime, and the branch name is deterministic so it would be the same branch.
    # Scoped to pull requests we could have opened, for the same reason as the reconcile above: a
    # stranger must not be able to stop us opening ours. Two operators on separate forks may
    # therefore both open one, which wastes a round; only one can land, and the other is refused
    # once the cursor moves.
    pr = own_pr(branch, states=("open",))
    # `--head owner:branch` for creation, so `gh` looks for the branch on the fork rather than on
    # the canonical repository, where it does not exist.
    head = f"{fork_owner}:{branch}" if fork_owner else branch
    if pr is not None:
        print(f"another worker opened it first: {pr['url']}")
        return EX_NOPROGRESS

    out = gh.gh(
        [
            "pr",
            "create",
            "--repo",
            gh.ROADMAP_REPO,
            "--base",
            "main",
            "--head",
            head,
            "--title",
            title,
            "--body",
            body,
        ]
    )
    print(out.strip())

    # Only now that ours is open: sweep the area's dead and superseded reports. Ordered this way so
    # a failure here costs a tidy-up, never a publication -- and so we never close the only open
    # report for an area.
    #
    # Without this the repository accumulates one unmergeable report per area per round, from two
    # directions: a sibling merging orphans every other report for that area instantly, and any
    # repository-wide breakage (a red `main` fails every report's `build`) makes each round open a
    # fresh one that also cannot merge, since the planner's staleness expiry stops the previous one
    # marking the area in flight. Neither ever closes itself. See `superseded_prs`.
    try:
        sweep(
            plan,
            branch,
            out.strip().splitlines()[-1] if out.strip() else "the new report",
        )
    except gh.GhError as exc:
        print(
            f"could not sweep superseded reports ({exc}); the new report is open regardless"
        )
    return 0
